name: RailSwitch
version: 3.0.0
main: sh.okx.railswitch.RailSwitchPlugin
api-version: 1.17
authors: [Okx, Protonull]
description: Easily make rail switches for automated destination selection
commands:
  dest: {}
  destadd: {}
  destdel: {}
  destbanner: {}
